[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -vv"
testpaths = [
    "tests",
    "integration",
]

[tool.flake8]
exclude = [".venv", "build"]
mas-line-length = 79

[tool.black]
line-length = 79
target-version = ["py311", "py312"]
exclude = '''
/(
    \.eggs
   | \.git
   | \.venv
   | _build
   | build 
   | dist
   | migrations 
)/
'''

[tool.isort]
profile = "black"
src_paths = ["dundie", "tests", "integration"]
multi_line_output = 3
